### PR TITLE
Updated header to match current university branding

### PR DESCRIPTION
**Pull request by andreaWaldren**
**JIRA Ticket**: (link) (:star:)
https://webapps.es.vt.edu/jira/browse/LIBTD-2372

# What does this Pull Request do? (:star:)
Updates the header to match the current branding for the university.

# What's the changes? (:star:)
Replaces previous header template code with the new code. This changes the logo in the header and changes the first link in the nav menu when expanded. Otherwise everything functions pretty much the same as before. There are also some changes for accessibility included in the new code, but those changes are invisible.

# How should this be tested?
Header should show VT logo followed by "university libraries" in the header at all screen sizes. "University libraries" should be the first link in the nav menu when expanded.

# Additional Notes:
branch is LIBTD-2372

# Interested parties
@yinlinchen 

(:star:) Required fields

### CODE REVIEW

**Comment by yinlinchen** [comment]
@andreaWaldren why there is no preview deployment in this PR?

**Comment by andreaWaldren** [comment]
@yinlinchen I don't know. It says that the step was skipped. I assumed it was something you had built in to the process to skip certain things. How do I force it to generate a preview?

**Review by ghoster — APPROVED** [review]
LGTM

**Review by yinlinchen — APPROVED** [review]
LGTM

**Pull request merged**
