### PR TITLE
Podcast media component and styles

### PR DESCRIPTION
**Pull request by andreaWaldren**
**JIRA Ticket**: (link) (:star:)
https://webapps.es.vt.edu/jira/browse/LIBTD-2099

* Other Relevant Links (Meeting note, project page, related pull requests, etc.)
wireframe - https://xd.adobe.com/view/518fe7b0-04fc-4066-a14d-c13bd8bb17c2-04dc/screen/822f3957-8c6a-4615-a651-605df08ab19b/

# What does this Pull Request do? (:star:)
Creates a component to render the podcasts on archive pages.

# What's the changes? (:star:)
-PodcastMediaElement - a customized media component that renders items from the podcast library. Changes styling and adds download button. Note that this component will also include a link to a transcript and links to other feeds for the show once that information is provided by the stakeholders.
-ArchivePage - implements PodcastMediaElement for the podcast library.

# How should this be tested?
Podcasts should display in the customized podcast page and other audio/video files in other libraries should render normally.

# Additional Notes:
Branch is LIBTD-2099

# Interested parties
@yinlinchen 

(:star:) Required fields

### CODE REVIEW

**Comment by yinlinchen** [comment]
@andreaWaldren is there a Podcass link in the demo site to see this new change?

**Comment by andreaWaldren** [comment]
@yinlinchen I just realized this problem too... I don't think there is a way to see this PR in the demo site since I have the component set to activate only on the podcast site. Is there a way to generate a preview link for the podcast site? If so, then /archive/m69aah01 would be the item to look at since it is the only one that I've updated in S3 to allow downloads.  If nothing else, you could pull my branch and run it locally?

**Comment by yinlinchen** [comment]
@andreaWaldren See https://libtd-2099.djf1n0m63xbku.amplifyapp.com/archive/m69bbh01 I can't see the diffidence with https://vtdlp-demo.cloud.lib.vt.edu/archive/m69bbh01

**Comment by andreaWaldren** [comment]
@yinlinchen Maybe I'm confused about how we want the podcast styles to be applied. With the way I have it set up now, because you are in the DEMO library, this item is jut an audio file. But when you are in the podcast library, it is a podcast. Another way I could define what is/is not a podcast would be to use the item_category property, but I see that in the demo library, /archive/m69bbh01 has been given an item_category of "Default", so it is still not a podcast. What do you think is the best way to define which audio files are podcasts?

**Comment by yinlinchen** [comment]
@yinlinchen Please update record `mfaau001001001test` in the Demo `Default` site so we can see that postcast record in the demo sit. The record `mfaau001001001test` is copied from `mfaau001001001` (archive/m69aah01 ) and put in the `Demo collection`

**Comment by andreaWaldren** [comment]
@yinlinchen I've tried to change the item category, but it appears that changing it from "Default" to "podcasts" makes the item irretrievable through the fetch because it filters for items with "Default" as their item_category. Is there another way to identify this audio file as a podcast?

**Comment by andreaWaldren** [comment]
@yinlinchen I reached out to Tingting today to get clarification the metadata element. So no need to ask her about this anymore as you had offered last week. This is good to go now.

**Review by yinlinchen — APPROVED** [review]
LGTM

**Pull request merged**
